### ISSUE TITLE
rtsp_example 用　vlc　播放就死掉了

### ISSUE THREAD

**Issue by jhkwei** [ireader/media-server#255]
rtsp_example 用　vlc　播放就死掉了,用　ffplay 播放没有事

run rtsp_example
[New Thread 0x7ffff7a2b640 (LWP 14024)]
[New Thread 0x7ffff722a640 (LWP 14025)]
[New Thread 0x7ffff6a29640 (LWP 14026)]
[New Thread 0x7ffff6228640 (LWP 14027)]
url:rtsp://127.0.0.1:8554/vod/s.mp4

Thread 5 "test" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6228640 (LWP 14027)]
MP4FileSource::SendRTCP (this=0x7ffff5823010, clock=11775024) at ../librtsp/test/media/mp4-file-source.cpp:408
408				m->transport->Send(true, rtcp, n);
(gdb) bt
#0  MP4FileSource::SendRTCP (this=0x7ffff5823010, clock=11775024) at ../librtsp/test/media/mp4-file-source.cpp:408
#1  0x00005555555a55d9 in rtsp_onplay (rtsp=0x7ffff00030a0, uri=0x7ffff00036e5 "rtsp://127.0.0.1:8554/stream=0", session=0x7ffff0003118 "0x7ffff5823010", npt=0x0, scale=0x0)
    at ../librtsp/test/rtsp-server-test.cpp:409
#2  0x0000555555645bf0 in rtsp_server_play (rtsp=0x7ffff00030a0, uri=0x7ffff00036e5 "rtsp://127.0.0.1:8554/stream=0") at source/server/rtsp-server-play.c:31
#3  0x0000555555645456 in rtsp_server_handle (rtsp=0x7ffff00030a0) at source/server/rtsp-server-handler.c:67
#4  0x0000555555644cf6 in rtsp_server_input (rtsp=0x7ffff00030a0, data=0x7ffff0001bf4, bytes=0x7ffff6225cd8) at source/server/rtsp-server.c:47
#5  0x00005555555da963 in rtsp_session_onrecv (param=0x7ffff0001b90, code=0, bytes=82) at ../librtsp/source/server/aio/rtsp-server-tcp.c:81
#6  0x00007ffff7fafb08 in aio_socket_onrecv (param=0x7ffff0002e90, code=0, bytes=82) at src/aio-transport.c:229
#7  0x00007ffff7fada39 in aio_handler_tcp (param=0x7ffff0002eb0, code=0, bytes=82) at src/aio-recv.c:83
#8  0x00007ffff7fb0e12 in epoll_recv (ctx=0x7ffff0002cb0, flags=1, error=0) at ../source/port/aio-socket-epoll.c:513
#9  0x00007ffff7fb056c in aio_socket_process (timeout=64) at ../source/port/aio-socket-epoll.c:328
#10 0x00007ffff7fafe48 in aio_worker (param=0x0) at src/aio-worker.c:19
#11 0x00007ffff7ac7b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#12 0x00007ffff7b59a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by ireader** [comment]
vlc命令是什么？

**Comment by jhkwei** [comment]
vlc 是一个播放器,　命令是这样的　vlc rtsp://127.0.0.1:8554/vod/s.mp4
