### ISSUE TITLE
RTSP 传输的问题

### ISSUE THREAD

**Issue by Jddl** [ireader/media-server#92]
码流大小为30Mbps,在使用TCP拉rtsp流的时候，1路是正常的，两路的时候CPU到90%以上，报错
Program received signal SIGPIPE, Broken pipe.
部分堆栈如下：
```
#0  0xb6dbd108 in send () from /lib/libc.so.0
#1  0xb2c2e98c in socket_send (sock=21, buf=0x2c8a94, len=114, flags=0)
    at ../include/sys/sock.h:325
#2  0xb2c2eebc in rtsp_session_send (ptr=0x2c76a0, data=0x2c8a94, bytes=114)
    at source/server/aio/rtsp-server-tcp.c:128
#3  0xb2c308ec in rtsp_server_reply2 (rtsp=0x2c89d0, code=200, header=0x0, 
    data=0x0, bytes=0) at source/server/rtsp-server.c:103
#4  0xb2c306c0 in rtsp_server_reply (rtsp=0x2c89d0, code=200)
    at source/server/rtsp-server.c:66
#5  0xb2c3040c in rtsp_server_reply_teardown (rtsp=0x2c89d0, code=200)
    at source/server/rtsp-server-teardown.c:17
#6  0xb2c1ee18 in rtsp_server_base::on_teardown (this=0x27b0a4, 
    rtsp=0x2c89d0, uri=0x2c8f79 "rtsp://192.168.13.30:8554/live/c", 
    session=0x2c8a0c "0x2cb080") at librtsp.cpp:185
#7  0xb2c1dba8 in rtsp_server_base::_on_teardown (this=0x27b0a4, 
    rtsp=0x2c89d0, uri=0x2c8f79 "rtsp://192.168.13.30:8554/live/c", 
    session=0x2c8a0c "0x2cb080") at librtsp.h:67
#8  0xb2c303d8 in rtsp_server_teardown (rtsp=0x2c89d0, 
    uri=0x2c8f79 "rtsp://192.168.13.30:8554/live/c")
    at source/server/rtsp-server-teardown.c:12
#9  0xb2c32d4c in rtsp_server_handle (rtsp=0x2c89d0)
    at source/server/rtsp-server-handler.c:73
#10 0xb2c305d4 in rtsp_server_input (rtsp=0x2c89d0, data=0x2c76c4, 
---Type <return> to continue, or q <return> to quit---
    bytes=0xa9047df8) at source/server/rtsp-server.c:47
#11 0xb2c2ecb4 in rtsp_session_onrecv (param=0x2c76a0, code=0, bytes=150)
    at source/server/aio/rtsp-server-tcp.c:81
#12 0xb2c4c4b8 in aio_socket_onrecv (param=0x2c8848, code=0, bytes=150)
    at src/aio-tcp-transport.c:172
#13 0xb2c4cb7c in aio_handler_tcp (param=0x2c8868, code=0, bytes=150)
    at src/aio-recv.c:81
#14 0xb2c4f010 in epoll_recv (ctx=0x2c8760, flags=1, error=32)
    at source/port/aio-socket-epoll.c:464
#15 0xb2c4e60c in aio_socket_process (timeout=64)
    at source/port/aio-socket-epoll.c:245
#16 0xb2c4c6c0 in aio_worker (param=0x0) at src/aio-worker.c:19
#17 0xb6fb857c in ?? () from /lib/libpthread.so.0
```
发送rtp代码如下
```
 std::lock_guard<std::mutex> lock(m_lock);
 std::map<std::string, rtsp_media_t>::iterator it;
 for (it = m_sessions.begin(); it != m_sessions.end(); it++)
 {
    static_pointer_cast<camera_live_source>(it->second.media)->push_rtp_data(rtpb.buffer, rtpb.size);
 }

```
sokect部分无论使用`socket_send_by_time`还是`socket_send_all_by_time`效果都一样

**Comment by ireader** [comment]
对方关闭连接后再发送数据就会SIGPIPE，这是正常的，把如下代码加到main函数中：
![image](https://user-images.githubusercontent.com/1535445/83890845-e650e300-a77e-11ea-8c71-ed400163e9da.png)

```
#if defined(OS_LINUX)
	struct sigaction sa;
	sa.sa_handler = SIG_IGN;
	sigaction(SIGCHLD, &sa, 0);
	sigaction(SIGPIPE, &sa, 0);
#endif
```
